services:
  - type: web
    name: telegram-quiz
    env: ruby
    region: frankfurt
    plan: starter
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails server -p $PORT -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEB_APP_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: PORT
        value: 3000
    healthCheckPath: /up
